# Generated by Django 3.1.5 on 2021-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Файл')),
            ],
        ),
    ]
